import type { ModelManifest } from './contracts.ts';

export const MODEL_ARTIFACT_POLICY = 'NO_AUTOMATIC_LARGE_MODEL_DOWNLOAD_IN_CI' as const;

const MODEL_IDS = {
  SAFE: '0198a5d3-4a00-7000-8000-000000000001',
  GRIP_CLIP_CONTROL: '0198a5d3-4a00-7000-8000-000000000002',
  SPECTRAL_PHASE_EXPERIMENT: '0198a5d3-4a00-7000-8000-000000000003',
  RECONSTRUCTION_EXPERIMENT: '0198a5d3-4a00-7000-8000-000000000004',
  LYTHAUS_STUDENT_V0: '0198a5d3-4a00-7000-8000-000000000005',
  GPT_OSS_20B_REASONER: '0198a5d3-4a00-7000-8000-000000000006',
  VISUAL_SEMANTIC_MODEL: '0198a5d3-4a00-7000-8000-000000000007',
} as const;

export const MODEL_REGISTRY: readonly ModelManifest[] = [
  {
    modelId: MODEL_IDS.SAFE as ModelManifest['modelId'],
    registryKey: 'SAFE',
    displayName: 'SAFE safety model interface',
    version: 'conceptual-v0',
    modelType: 'CLASSIFIER',
    role: 'SAFETY',
    source: 'provider-neutral conceptual entry; no artifact bundled',
    licence: 'TBD',
    weightLicence: null,
    commercialUseStatus: 'NOT_REVIEWED',
    inputContract: 'image bytes or decoded image reference',
    outputContract: 'provider-neutral moderation evidence',
    artifactSha256: null,
    evaluationStatus: 'NOT_STARTED',
    deploymentStatus: 'NOT_DEPLOYED',
    rollbackVersion: null,
    approvalTimestamp: null,
  },
  {
    modelId: MODEL_IDS.GRIP_CLIP_CONTROL as ModelManifest['modelId'],
    registryKey: 'GRIP_CLIP_CONTROL',
    displayName: 'GRIP CLIP control embedding interface',
    version: 'conceptual-v0',
    modelType: 'EMBEDDING',
    role: 'FORENSICS',
    source: 'provider-neutral conceptual entry; frozen weights required later',
    licence: 'TBD',
    weightLicence: null,
    commercialUseStatus: 'NOT_REVIEWED',
    inputContract: 'decoded image tensor',
    outputContract: 'embedding and applicability metadata',
    artifactSha256: null,
    evaluationStatus: 'NOT_STARTED',
    deploymentStatus: 'NOT_DEPLOYED',
    rollbackVersion: null,
    approvalTimestamp: null,
  },
  {
    modelId: MODEL_IDS.SPECTRAL_PHASE_EXPERIMENT as ModelManifest['modelId'],
    registryKey: 'SPECTRAL_PHASE_EXPERIMENT',
    displayName: 'Spectral phase experiment',
    version: 'v0',
    modelType: 'SPECTRAL',
    role: 'FORENSICS',
    source: 'Lythaus deterministic research interface',
    licence: 'Lythaus-owned code; weights not applicable',
    weightLicence: null,
    commercialUseStatus: 'APPROVED',
    inputContract: 'ForensicFeatureBundle spectral inputs',
    outputContract: 'spectral evidence with robustness grade',
    artifactSha256: null,
    evaluationStatus: 'SHADOW_ONLY',
    deploymentStatus: 'NOT_DEPLOYED',
    rollbackVersion: null,
    approvalTimestamp: null,
  },
  {
    modelId: MODEL_IDS.RECONSTRUCTION_EXPERIMENT as ModelManifest['modelId'],
    registryKey: 'RECONSTRUCTION_EXPERIMENT',
    displayName: 'Reconstruction detector experiment',
    version: 'v0',
    modelType: 'RECONSTRUCTION',
    role: 'FORENSICS',
    source: 'provider-neutral conceptual entry; no artifact bundled',
    licence: 'TBD',
    weightLicence: null,
    commercialUseStatus: 'NOT_REVIEWED',
    inputContract: 'decoded image and local region candidates',
    outputContract: 'regional reconstruction evidence',
    artifactSha256: null,
    evaluationStatus: 'NOT_STARTED',
    deploymentStatus: 'NOT_DEPLOYED',
    rollbackVersion: null,
    approvalTimestamp: null,
  },
  {
    modelId: MODEL_IDS.LYTHAUS_STUDENT_V0 as ModelManifest['modelId'],
    registryKey: 'LYTHAUS_STUDENT_V0',
    displayName: 'Lythaus student fusion model',
    version: 'v0',
    modelType: 'FUSION',
    role: 'FORENSICS',
    source: 'Lythaus-owned future distillation target',
    licence: 'Lythaus-owned',
    weightLicence: 'TBD',
    commercialUseStatus: 'NOT_REVIEWED',
    inputContract: 'precomputed teacher evidence and deterministic features',
    outputContract: 'calibrated evidence recommendation with abstention',
    artifactSha256: null,
    evaluationStatus: 'NOT_STARTED',
    deploymentStatus: 'NOT_DEPLOYED',
    rollbackVersion: null,
    approvalTimestamp: null,
  },
  {
    modelId: MODEL_IDS.GPT_OSS_20B_REASONER as ModelManifest['modelId'],
    registryKey: 'GPT_OSS_20B_REASONER',
    displayName: 'GPT-OSS 20B evidence reasoner',
    version: 'candidate-@cf/openai/gpt-oss-20b',
    modelType: 'REASONER',
    role: 'JUDGE',
    source: 'Workers AI candidate; provider adapter remains replaceable',
    licence: 'Verify before production use',
    weightLicence: 'Verify before production use',
    commercialUseStatus: 'NOT_REVIEWED',
    inputContract: 'versioned evidence records and policy context',
    outputContract: 'structured recommendation and contradiction codes',
    artifactSha256: null,
    evaluationStatus: 'SHADOW_ONLY',
    deploymentStatus: 'SHADOW',
    rollbackVersion: null,
    approvalTimestamp: null,
  },
  {
    modelId: MODEL_IDS.VISUAL_SEMANTIC_MODEL as ModelManifest['modelId'],
    registryKey: 'VISUAL_SEMANTIC_MODEL',
    displayName: 'Visual semantic model interface',
    version: 'conceptual-v0',
    modelType: 'SEMANTIC_VISION',
    role: 'FORENSICS',
    source: 'provider-neutral conceptual entry; no artifact bundled',
    licence: 'TBD',
    weightLicence: null,
    commercialUseStatus: 'NOT_REVIEWED',
    inputContract: 'decoded image and evidence bundle reference',
    outputContract: 'semantic context evidence only',
    artifactSha256: null,
    evaluationStatus: 'NOT_STARTED',
    deploymentStatus: 'NOT_DEPLOYED',
    rollbackVersion: null,
    approvalTimestamp: null,
  },
];

export function getModelManifest(registryKey: string): ModelManifest | null {
  return MODEL_REGISTRY.find((model) => model.registryKey === registryKey) ?? null;
}

export function assertModelArtifactPolicy(input: { artifactAvailable: boolean; allowLargeDownload: boolean }): void {
  if (input.artifactAvailable && input.allowLargeDownload) return;
  if (input.allowLargeDownload) throw new Error(`${MODEL_ARTIFACT_POLICY}:artifact_not_present`);
}
