import type { ModelManifest } from './contracts.ts';
import { isUuidV7 } from './uuid.ts';

export const MODEL_ARTIFACT_POLICY = 'NO_AUTOMATIC_LARGE_MODEL_DOWNLOAD_IN_CI' as const;
export const MODEL_REGISTRY_ASSESSMENT_DATE = '2026-08-09' as const;

const MODEL_IDS = {
  SAFE: '0198a5d3-4a00-7000-8000-000000000001',
  GRIP_CLIP_CONTROL: '0198a5d3-4a00-7000-8000-000000000002',
  SPECTRAL_PHASE_EXPERIMENT: '0198a5d3-4a00-7000-8000-000000000003',
  RECONSTRUCTION_EXPERIMENT: '0198a5d3-4a00-7000-8000-000000000004',
  LYTHAUS_STUDENT_V0: '0198a5d3-4a00-7000-8000-000000000005',
  GPT_OSS_20B_REASONER: '0198a5d3-4a00-7000-8000-000000000006',
  VISUAL_SEMANTIC_MODEL: '0198a5d3-4a00-7000-8000-000000000007',
  RECONSTRUCTION_DIRE: '0198a5d3-4a00-7000-8000-000000000008',
  RECONSTRUCTION_LARE2: '0198a5d3-4a00-7000-8000-000000000009',
  RECONSTRUCTION_ADRD: '0198a5d3-4a00-7000-8000-000000000010',
  CAMERA_FORENSICS_DETERMINISTIC: '0198a5d3-4a00-7000-8000-000000000011',
} as const;

const COMMON = {
  artifactSha256: null,
  evaluationStatus: 'NOT_STARTED' as const,
  deploymentStatus: 'NOT_DEPLOYED' as const,
  rollbackVersion: null,
  approvalTimestamp: null,
  sourceAccessedAt: MODEL_REGISTRY_ASSESSMENT_DATE,
};

export const MODEL_REGISTRY: readonly ModelManifest[] = [
  {
    ...COMMON,
    modelId: MODEL_IDS.SAFE as ModelManifest['modelId'],
    registryKey: 'SAFE',
    displayName: 'SAFE synthetic image detector',
    version: 'upstream-review-v0',
    modelType: 'CLASSIFIER',
    role: 'FORENSICS',
    researchRole: 'TEACHER',
    source: 'https://github.com/ouxiang-li/safe',
    paperUrl: 'https://arxiv.org/abs/2408.06741',
    codeRepositoryUrl: 'https://github.com/ouxiang-li/safe',
    licence: 'Apache-2.0 (repository code)',
    licenceEvidenceUrl: 'https://github.com/ouxiang-li/safe',
    weightLicence: 'UNKNOWN_SEPARATE_CHECKPOINT_REVIEW_REQUIRED',
    weightLicenceEvidenceUrl: 'https://github.com/ouxiang-li/safe/tree/main/checkpoint',
    commercialUseStatus: 'UNKNOWN',
    distillationSuitability: 'CONDITIONAL',
    inputContract: 'decoded RGB image tensor; upstream resolution must be pinned',
    outputContract: 'synthetic-origin score and applicability evidence',
    architecture: 'Transformation-preserved and augmented feature classifier; exact upstream graph to pin',
    parameterCount: null,
    weightSizeMb: null,
    runtimeRequirements: 'PyTorch, torchvision, upstream checkpoint and preprocessing',
    gpuRequirement: 'Upstream training instructions use four GPUs; inference unverified',
    cpuFeasibility: 'LIMITED',
    inputResolution: 'Upstream evaluation resolution; record exact value before use',
    strengths: ['transformation-oriented design', 'unseen/current generator evaluation', 'research reproducibility'],
    weaknesses: ['checkpoint/data rights unverified', 'not CPU-first', 'no Lythaus benchmark result'],
    transformationRobustness: 'Promising upstream evidence; must be independently measured',
    unseenGeneratorEvidence: 'Reported by upstream on multiple generator families; not independently verified',
    localisationCapability: 'Image-level; local regions not established',
    deploymentFeasibility: 'Not suitable for the lite proof without a bounded compact artefact',
    teacherSuitability: 'Conditional teacher after licence and reproducibility gates',
    productionSuitability: 'Not a production candidate in WP002',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.GRIP_CLIP_CONTROL as ModelManifest['modelId'],
    registryKey: 'GRIP_CLIP_CONTROL',
    displayName: 'GRIP CLIP synthetic-image control',
    version: 'upstream-review-v0',
    modelType: 'EMBEDDING',
    role: 'FORENSICS',
    researchRole: 'CONTROL',
    source: 'https://github.com/grip-unina/ClipBased-SyntheticImageDetection',
    paperUrl: 'https://arxiv.org/abs/2312.00195',
    codeRepositoryUrl: 'https://github.com/grip-unina/ClipBased-SyntheticImageDetection',
    licence: 'Apache-2.0 (repository code)',
    licenceEvidenceUrl: 'https://github.com/grip-unina/ClipBased-SyntheticImageDetection/blob/main/LICENSE.md',
    weightLicence: 'UNKNOWN_UPSTREAM_CLIP_AND_CHECKPOINT_REVIEW_REQUIRED',
    weightLicenceEvidenceUrl: 'https://github.com/grip-unina/ClipBased-SyntheticImageDetection/tree/main/weights',
    commercialUseStatus: 'UNKNOWN',
    distillationSuitability: 'CONDITIONAL',
    inputContract: 'decoded image tensor and CLIP preprocessing',
    outputContract: 'embedding, log-likelihood score, and applicability metadata',
    architecture: 'Pretrained CLIP features with lightweight detector/classifier',
    parameterCount: null,
    weightSizeMb: null,
    runtimeRequirements: 'Python, PyTorch, torchvision, timm, open_clip and checkpoint files',
    gpuRequirement: 'Upstream examples use CUDA; CPU inference must be benchmarked',
    cpuFeasibility: 'LIMITED',
    inputResolution: 'CLIP backbone resolution; pin exact variant before use',
    strengths: ['independent control relative to SAFE', 'reported unseen-generator robustness', 'reported degraded-image robustness'],
    weaknesses: ['weight/data licence lineage incomplete', 'CLIP dependency', 'camera and local-edit coverage unknown'],
    transformationRobustness: 'Promising upstream evidence; requires Lythaus transformation matrix',
    unseenGeneratorEvidence: 'Reported for commercial and unseen generators upstream',
    localisationCapability: 'Image-level; no accepted regional mask contract',
    deploymentFeasibility: 'Not suitable for the lite proof until CPU and weight size are verified',
    teacherSuitability: 'Conditional control/teacher after licence gate',
    productionSuitability: 'Not a production candidate in WP002',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.SPECTRAL_PHASE_EXPERIMENT as ModelManifest['modelId'],
    registryKey: 'SPECTRAL_PHASE_EXPERIMENT',
    displayName: 'Lythaus spectral and phase baseline',
    version: 'v1',
    modelType: 'SPECTRAL',
    role: 'FORENSICS',
    researchRole: 'BASELINE',
    source: 'Lythaus-owned deterministic feature implementation',
    paperUrl: null,
    codeRepositoryUrl: null,
    licence: 'Lythaus-owned code; no external weights',
    licenceEvidenceUrl: null,
    weightLicence: null,
    weightLicenceEvidenceUrl: null,
    commercialUseStatus: 'APPROVED',
    distillationSuitability: 'SUITABLE',
    inputContract: 'ForensicFeatureBundle spectral, DCT, wavelet and residual features',
    outputContract: 'deterministic feature vector and robustness measurements',
    architecture: 'Multi-scale FFT magnitude/phase, DCT, wavelet and high-pass statistics',
    parameterCount: 0,
    weightSizeMb: 0,
    runtimeRequirements: 'TypeScript/JavaScript deterministic image feature path',
    gpuRequirement: 'None',
    cpuFeasibility: 'FEASIBLE',
    inputResolution: 'Bounded decoded image and image pyramid',
    strengths: ['provider independent', 'CPU feasible', 'auditable and deterministic'],
    weaknesses: ['not a standalone learned detector', 'phase and compression sensitivity require calibration'],
    transformationRobustness: 'Measured through transformation lab; no claim until benchmarked',
    unseenGeneratorEvidence: 'Unknown until benchmark material exists',
    localisationCapability: 'Feature-level; regional extension remains future work',
    deploymentFeasibility: 'Suitable for the deterministic Container proof',
    teacherSuitability: 'Suitable as a student input and control signal',
    productionSuitability: 'Evidence only; no enforcement authority',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.RECONSTRUCTION_EXPERIMENT as ModelManifest['modelId'],
    registryKey: 'RECONSTRUCTION_EXPERIMENT',
    displayName: 'Reconstruction-detector family interface',
    version: 'family-review-v0',
    modelType: 'RECONSTRUCTION',
    role: 'FORENSICS',
    researchRole: 'EXPERIMENTAL',
    source: 'DIRE, LaRE2 (LaRE squared), ADRD and newer reconstruction research family',
    paperUrl: 'https://arxiv.org/abs/2303.09295',
    codeRepositoryUrl: null,
    licence: 'Candidate-specific review required',
    licenceEvidenceUrl: null,
    weightLicence: 'UNKNOWN',
    weightLicenceEvidenceUrl: null,
    commercialUseStatus: 'UNKNOWN',
    distillationSuitability: 'UNKNOWN',
    inputContract: 'decoded image and optional local region candidates',
    outputContract: 'reconstruction discrepancy evidence with compute metadata',
    architecture: 'Candidate family abstraction; implementation intentionally unselected',
    parameterCount: null,
    weightSizeMb: null,
    runtimeRequirements: 'Candidate-dependent diffusion or latent reconstruction runtime',
    gpuRequirement: 'Likely GPU for practical latency; must measure',
    cpuFeasibility: 'UNKNOWN',
    inputResolution: 'Candidate-dependent',
    strengths: ['can expose reconstruction behaviour', 'potential mixed-origin escalation signal'],
    weaknesses: ['high latency/cost risk', 'candidate and weight licence variance', 'possible generator bias'],
    transformationRobustness: 'Must be compared under the full WP002 matrix',
    unseenGeneratorEvidence: 'Candidate-specific and not yet verified',
    localisationCapability: 'Potentially regional, candidate-dependent',
    deploymentFeasibility: 'Occasional escalation only; not the lite proof',
    teacherSuitability: 'Conditional after candidate selection and rights review',
    productionSuitability: 'Research-only in WP002',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.RECONSTRUCTION_DIRE as ModelManifest['modelId'],
    registryKey: 'RECONSTRUCTION_DIRE',
    displayName: 'DIRE reconstruction candidate',
    version: 'paper-review-v0',
    modelType: 'RECONSTRUCTION',
    role: 'FORENSICS',
    researchRole: 'EXPERIMENTAL',
    source: 'https://github.com/ZhendongWang6/DIRE',
    paperUrl: 'https://arxiv.org/abs/2303.09295',
    codeRepositoryUrl: 'https://github.com/ZhendongWang6/DIRE',
    licence: 'Candidate repository licence requires verification',
    licenceEvidenceUrl: 'https://github.com/ZhendongWang6/DIRE',
    weightLicence: 'UNKNOWN',
    weightLicenceEvidenceUrl: null,
    commercialUseStatus: 'UNKNOWN',
    distillationSuitability: 'CONDITIONAL',
    inputContract: 'image plus diffusion reconstruction pipeline',
    outputContract: 'diffusion reconstruction error evidence',
    architecture: 'Diffusion reconstruction error representation',
    parameterCount: null,
    weightSizeMb: null,
    runtimeRequirements: 'Pretrained diffusion model and reconstruction passes',
    gpuRequirement: 'Expected GPU for practical latency; measure before use',
    cpuFeasibility: 'INFEASIBLE',
    inputResolution: 'Candidate-dependent',
    strengths: ['unseen-diffusion research evidence', 'clear reconstruction signal'],
    weaknesses: ['expensive reconstruction dependency', 'licence and robustness must be rechecked'],
    transformationRobustness: 'Reported in paper; must be independently measured',
    unseenGeneratorEvidence: 'Reported on unseen diffusion families',
    localisationCapability: 'Not established as a regional mask output',
    deploymentFeasibility: 'Occasional GPU/offline escalation only',
    teacherSuitability: 'Conditional teacher for precomputed outputs',
    productionSuitability: 'Not a production candidate in WP002',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.RECONSTRUCTION_LARE2 as ModelManifest['modelId'],
    registryKey: 'RECONSTRUCTION_LARE2',
    displayName: 'LaRE2 (LaRE squared) latent reconstruction candidate',
    version: 'paper-review-v0',
    modelType: 'RECONSTRUCTION',
    role: 'FORENSICS',
    researchRole: 'EXPERIMENTAL',
    source: 'https://github.com/luo3300612/LaRE',
    paperUrl: 'https://arxiv.org/abs/2403.17465',
    codeRepositoryUrl: 'https://github.com/luo3300612/LaRE',
    licence: 'Candidate repository licence requires verification',
    licenceEvidenceUrl: 'https://github.com/luo3300612/LaRE',
    weightLicence: 'UNKNOWN',
    weightLicenceEvidenceUrl: null,
    commercialUseStatus: 'UNKNOWN',
    distillationSuitability: 'CONDITIONAL',
    inputContract: 'image and latent reconstruction feature pipeline',
    outputContract: 'latent reconstruction error and refined detection evidence',
    architecture: 'Latent Reconstruction Error with error-guided feature refinement',
    parameterCount: null,
    weightSizeMb: null,
    runtimeRequirements: 'Latent reconstruction backbone and detector runtime',
    gpuRequirement: 'Likely GPU for practical latency; measure before use',
    cpuFeasibility: 'UNKNOWN',
    inputResolution: 'Candidate-dependent',
    strengths: ['lower extraction cost claim relative to pixel reconstruction', 'latent feature signal'],
    weaknesses: ['rights and runtime unverified', 'diffusion-family generalisation may vary'],
    transformationRobustness: 'Unknown until full matrix evaluation',
    unseenGeneratorEvidence: 'Reported across eight generator families in paper; not Lythaus evidence',
    localisationCapability: 'Potential feature localisation; not accepted as a mask contract',
    deploymentFeasibility: 'Potential occasional escalation if bounded benchmark passes',
    teacherSuitability: 'Conditional teacher for precomputed outputs',
    productionSuitability: 'Not a production candidate in WP002',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.RECONSTRUCTION_ADRD as ModelManifest['modelId'],
    registryKey: 'RECONSTRUCTION_ADRD',
    displayName: 'ADRD perturbation reconstruction watchlist',
    version: 'paper-review-v0',
    modelType: 'RECONSTRUCTION',
    role: 'FORENSICS',
    researchRole: 'WATCHLIST',
    source: 'https://github.com/ezell-chou/adrd',
    paperUrl: 'https://pubmed.ncbi.nlm.nih.gov/42447175/',
    codeRepositoryUrl: 'https://github.com/ezell-chou/adrd',
    licence: 'Current code licence requires verification',
    licenceEvidenceUrl: null,
    weightLicence: 'UNKNOWN',
    weightLicenceEvidenceUrl: null,
    commercialUseStatus: 'UNKNOWN',
    distillationSuitability: 'UNKNOWN',
    inputContract: 'image and controlled reconstruction perturbations',
    outputContract: 'reconstruction discrepancy stability evidence',
    architecture: 'Adversarial perturbation-induced reconstruction discrepancy',
    parameterCount: null,
    weightSizeMb: null,
    runtimeRequirements: 'Reconstruction model plus perturbation passes',
    gpuRequirement: 'Expected GPU for practical latency; measure before use',
    cpuFeasibility: 'UNKNOWN',
    inputResolution: 'Candidate-dependent',
    strengths: ['tests reconstruction behaviour under perturbation', 'complements absolute reconstruction error'],
    weaknesses: ['new evidence base', 'rights, compute, and transformation behaviour unknown'],
    transformationRobustness: 'Research question; no Lythaus result',
    unseenGeneratorEvidence: 'Unknown until reproduction',
    localisationCapability: 'Unknown',
    deploymentFeasibility: 'Research-only watchlist',
    teacherSuitability: 'Not yet assessed',
    productionSuitability: 'Not commercially assessed',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.CAMERA_FORENSICS_DETERMINISTIC as ModelManifest['modelId'],
    registryKey: 'CAMERA_FORENSICS_DETERMINISTIC',
    displayName: 'Lythaus camera-origin evidence branch',
    version: 'v0',
    modelType: 'SPECTRAL',
    role: 'FORENSICS',
    researchRole: 'BASELINE',
    source: 'Lythaus-owned deterministic evidence contract',
    paperUrl: null,
    codeRepositoryUrl: null,
    licence: 'Lythaus-owned code; no external weights',
    licenceEvidenceUrl: null,
    weightLicence: null,
    weightLicenceEvidenceUrl: null,
    commercialUseStatus: 'APPROVED',
    distillationSuitability: 'SUITABLE',
    inputContract: 'file provenance, decoded pixels, metadata, noise and screen indicators',
    outputContract: 'camera evidence applicability and dual-axis origin evidence',
    architecture: 'Deterministic CFA, demosaicing, noise, optics, moire and pipeline features',
    parameterCount: 0,
    weightSizeMb: 0,
    runtimeRequirements: 'Bounded CPU image preprocessing',
    gpuRequirement: 'None for v0',
    cpuFeasibility: 'FEASIBLE',
    inputResolution: 'Decoded image and available metadata',
    strengths: ['transparent evidence', 'supports camera/screen distinction', 'no AI-origin inversion'],
    weaknesses: ['PRNU is device-dependent', 'metadata may be absent', 'camera authentication is unsolved'],
    transformationRobustness: 'Feature-specific; must be reported per transformation',
    unseenGeneratorEvidence: 'Not applicable as a generator classifier',
    localisationCapability: 'Screen/moire regions may be regional in future',
    deploymentFeasibility: 'Suitable for deterministic proof and preflight',
    teacherSuitability: 'Suitable student input; not a teacher model',
    productionSuitability: 'Evidence only; no enforcement authority',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.LYTHAUS_STUDENT_V0 as ModelManifest['modelId'],
    registryKey: 'LYTHAUS_STUDENT_V0',
    displayName: 'Lythaus student fusion model',
    version: 'v0',
    modelType: 'FUSION',
    role: 'FORENSICS',
    researchRole: 'EXPERIMENTAL',
    source: 'Lythaus-owned future distillation target',
    paperUrl: null,
    codeRepositoryUrl: null,
    licence: 'Lythaus-owned future code',
    licenceEvidenceUrl: null,
    weightLicence: 'Not trained',
    weightLicenceEvidenceUrl: null,
    commercialUseStatus: 'NOT_REVIEWED',
    distillationSuitability: 'SUITABLE',
    inputContract: 'teacher scores, deterministic features, camera features, and spectral features',
    outputContract: 'calibrated evidence recommendation with abstention',
    architecture: 'Small CPU fusion model; v0.5 frozen embeddings; v1 compact branches',
    parameterCount: null,
    weightSizeMb: null,
    runtimeRequirements: 'Classical ML/small neural network on approved precomputed features',
    gpuRequirement: 'None for v0 design',
    cpuFeasibility: 'FEASIBLE',
    inputResolution: 'Feature contract dependent',
    strengths: ['low-cost inference', 'auditable teacher disagreement', 'Lythaus-owned output'],
    weaknesses: ['no training data yet', 'teacher rights and calibration gates unresolved'],
    transformationRobustness: 'Must be trained/evaluated on grouped variants',
    unseenGeneratorEvidence: 'Unknown until benchmark run',
    localisationCapability: 'Inherits teacher/local-feature inputs',
    deploymentFeasibility: 'Future CPU candidate only',
    teacherSuitability: 'Student target, not teacher',
    productionSuitability: 'Not trained or eligible in WP002',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.GPT_OSS_20B_REASONER as ModelManifest['modelId'],
    registryKey: 'GPT_OSS_20B_REASONER',
    displayName: 'GPT-OSS 20B evidence reasoner',
    version: 'candidate-@cf/openai/gpt-oss-20b',
    modelType: 'REASONER',
    role: 'JUDGE',
    researchRole: 'WATCHLIST',
    source: 'Workers AI candidate; provider adapter remains replaceable',
    paperUrl: null,
    codeRepositoryUrl: null,
    licence: 'Verify current model and provider terms before use',
    licenceEvidenceUrl: null,
    weightLicence: 'Provider/model terms require verification',
    weightLicenceEvidenceUrl: null,
    commercialUseStatus: 'UNKNOWN',
    distillationSuitability: 'UNSUITABLE',
    inputContract: 'versioned evidence records and policy context',
    outputContract: 'structured recommendation and contradiction codes',
    architecture: '20B language reasoner adapter; no direct authorship detector role',
    parameterCount: 20_000_000_000,
    weightSizeMb: null,
    runtimeRequirements: 'Workers AI remote inference or approved equivalent',
    gpuRequirement: 'Provider-managed; not local training',
    cpuFeasibility: 'INFEASIBLE',
    inputResolution: 'Evidence JSON, not raw image pixels',
    strengths: ['evidence reconciliation', 'contradiction explanation', 'policy-context separation'],
    weaknesses: ['usage cost', 'provider terms', 'not a sole detector or enforcer'],
    transformationRobustness: 'Inherited from supplied evidence; not a detector metric',
    unseenGeneratorEvidence: 'Not applicable as a forensic detector',
    localisationCapability: 'Can reason over supplied regional evidence only',
    deploymentFeasibility: 'Shadow-only adapter',
    teacherSuitability: 'Not suitable for commercial image-model distillation without terms',
    productionSuitability: 'Judge recommendation only; deterministic code enforces policy',
  },
  {
    ...COMMON,
    modelId: MODEL_IDS.VISUAL_SEMANTIC_MODEL as ModelManifest['modelId'],
    registryKey: 'VISUAL_SEMANTIC_MODEL',
    displayName: 'Visual semantic model interface',
    version: 'conceptual-v0',
    modelType: 'SEMANTIC_VISION',
    role: 'FORENSICS',
    researchRole: 'WATCHLIST',
    source: 'Provider-independent conceptual interface; no artifact bundled',
    paperUrl: null,
    codeRepositoryUrl: null,
    licence: 'TBD',
    licenceEvidenceUrl: null,
    weightLicence: null,
    weightLicenceEvidenceUrl: null,
    commercialUseStatus: 'NOT_REVIEWED',
    distillationSuitability: 'UNKNOWN',
    inputContract: 'decoded image and evidence bundle reference',
    outputContract: 'semantic context evidence only',
    architecture: 'Provider-neutral semantic vision adapter',
    parameterCount: null,
    weightSizeMb: null,
    runtimeRequirements: 'Provider/model dependent',
    gpuRequirement: 'Provider/model dependent',
    cpuFeasibility: 'UNKNOWN',
    inputResolution: 'Provider/model dependent',
    strengths: ['future semantic context', 'provider neutrality'],
    weaknesses: ['no licence or runtime selected', 'semantic evidence is not provenance proof'],
    transformationRobustness: 'Unknown',
    unseenGeneratorEvidence: 'Unknown',
    localisationCapability: 'Provider-dependent',
    deploymentFeasibility: 'Not deployed',
    teacherSuitability: 'Unknown',
    productionSuitability: 'Not assessed',
  },
];

export function getModelManifest(registryKey: string): ModelManifest | null {
  return MODEL_REGISTRY.find((model) => model.registryKey === registryKey) ?? null;
}

export function assertModelArtifactPolicy(input: { artifactAvailable: boolean; allowLargeDownload: boolean }): void {
  if (input.artifactAvailable && input.allowLargeDownload) return;
  if (input.allowLargeDownload) throw new Error(`${MODEL_ARTIFACT_POLICY}:artifact_not_present`);
}

export function validateModelManifest(model: ModelManifest): void {
  if (!isUuidV7(model.modelId)) throw new Error(`model_id_not_uuid_v7:${model.registryKey}`);
  if (!model.registryKey || !model.displayName || !model.version) throw new Error(`model_identity_missing:${model.registryKey}`);
  if (model.commercialUseStatus === 'APPROVED' && model.weightLicence === null && model.modelType !== 'SPECTRAL') {
    throw new Error(`approved_model_missing_weight_licence:${model.registryKey}`);
  }
  if (model.deploymentStatus === 'PRODUCTION_REVIEW_ONLY') throw new Error(`production_review_status_forbidden:${model.registryKey}`);
  if (model.researchRole === 'NOT_COMMERCIALLY_USABLE' && model.commercialUseStatus === 'APPROVED') {
    throw new Error(`commercial_role_conflict:${model.registryKey}`);
  }
}

export function assertModelRegistryPolicy(): void {
  for (const model of MODEL_REGISTRY) validateModelManifest(model);
  if (MODEL_REGISTRY.some((model) => model.artifactSha256 !== null)) throw new Error('model_artifact_must_not_be_bundled_in_wp002');
}
